spring.application.name=SqsDemoApp
server.port:9191
aws.region=ap-south-1    
aws.sqs.queueName=weekly-task-queue
aws.access.key=${AWS_ACCESS_KEY:your_access_key}
aws.secret.key=${AWS_SECRET_KEY:your_secret_key}
#new  comment